# Generated by Django 3.2 on 2021-06-20 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_tablecolumn'),
    ]

    operations = [
        migrations.AddField(
            model_name='tablecolumn',
            name='data_type',
            field=models.TextField(blank=True, choices=[('int', 'Целое число'), ('float8', 'Число с плавающей точкой'), ('varchar(256)', 'Char'), ('text', 'Текст')]),
        ),
        migrations.AlterField(
            model_name='database',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
