# Generated by Django 3.2 on 2021-06-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0004_auto_20210620_2308'),
    ]

    operations = [
        migrations.CreateModel(
            name='TableElement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
            ],
        ),
    ]
